name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: | 
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            npm version patch -m "[RELEASE] %s"
      - name: Mirror to GitHub
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: 
            https://github.com/verschhh/R-TypeTest.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
