name: Mirroring

on: [push, delete]

jobs:
  to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror to GitHub
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: 
            git@github.com:EpitechPromo2026/https://github.com/EpitechPromo2026/B-CPP-500-BER-5-2-rtype-leonard.verschuere.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
