name: CI_on_pull_request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for a full clone
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN provided by GitHub

      - name: Run a one-line command to mirror the repo
        run: |
          git clone --mirror "https://github.com/EpitechPromo2026/B-CPP-500-BER-5-2-rtype-leonard.verschuere.git"
